apiVersion: v1
kind: ReplicationController
metadata:
  name: stats
spec:
  replicas: 1
  selector:
    name: stats
  template:
    metadata:
      labels:
        name: stats
    spec:
      containers:
      - name: stats
        image: gcr.io/<project-id>/stats:latest
        ports:
        - containerPort: 5000
        resources:
          limits:
            cpu: "0.1"
        command:
        - "/gopath/src/github.com/rlguarino/shortener/stats/stats"
        - "-c" 
        - "/gopath/src/github.com/rlguarino/shortener/kubernetes-example/stats-config.json"

