apiVersion: v1
kind: ReplicationController
metadata:
  name: urlservice
spec:
  replicas: 1
  selector:
    name: urlservice
  template:
    metadata:
      labels:
        name: urlservice
    spec:
      containers:
      - name: urlservice
        image: gcr.io/<project-id>/urlservice:latest
        ports:
        - containerPort: 5000
        resources:
          limits:
            cpu: "0.1"
        command:
        - "/gopath/src/github.com/rlguarino/shortener/urlservice/urlservice"
        - "-c" 
        - "/gopath/src/github.com/rlguarino/shortener/kubernetes-example/urlservice-config.json"

